version: "3"
services:
  backend:
    build: .
    ports:
      - "9001:9001"
  mysql:
    platform: linux/x86_64
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin
    volumes:
      - ../database-model:/docker-entrypoint-initdb.d